# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "steam_powered:cogbot",
    "alexsmobs:snow_leopard",
    "aquaculture:pink_salmon",
    "irons_spellbooks:archevoker",
    "endermanoverhaul:flower_fields_enderman",
    "gore:zombiewithoutarms",
    "irons_spellbooks:catacombs_zombie",
    "endermanoverhaul:desert_enderman",
    "ars_nouveau:familiar_wixie",
    "alexsmobs:endergrade",
    "minecraft:horse",
    "player_companions:samurai",
    "rustic_engineer:dragon_fly",
    "aquaculture:muskellunge",
    "minecraft:llama",
    "alexscaves:underzealot",
    "alexsmobs:skreecher",
    "steam_powered:lost_diver",
    "minecraft:tadpole",
    "aquamirae:maw",
    "alexscaves:corrodent",
    "alexsmobs:hammerhead_shark",
    "alexscaves:magnetron",
    "naturalist:bear",
    "graveyard:nightmare",
    "alexsmobs:grizzly_bear",
    "samurai_dynasty:kawauso",
    "naturalist:vulture",
    "alexsmobs:murmur_head",
    "naturalist:zebra",
    "steam_powered:bog_dweller",
    "gore:cutted_vertical_zombie",
    "gore:husk_without_arms",
    "graveyard:reaper",
    "ars_nouveau:gift_starby",
    "samurai_dynasty:oni",
    "minecraft:mooshroom",
    "minecraft:axolotl",
    "burnt:fire_devil",
    "irons_spellbooks:summoned_vex",
    "alexsmobs:gorilla",
    "gore:zombie_without_head",
    "alexsmobs:cosmic_cod",
    "ars_nouveau:drygmy",
    "epicfight:wither_skeleton_minion",
    "aquaculture:pacific_halibut",
    "alexscaves:deep_one_mage",
    "naturalist:cardinal",
    "alexsmobs:kangaroo",
    "endermanoverhaul:hammerhead_pet_enderman",
    "creeperoverhaul:spruce_creeper",
    "ars_nouveau:wilden_boss",
    "alexsmobs:hummingbird",
    "iceandfire:siren",
    "mutantmonsters:mutant_zombie",
    "gore:multiple_cuts_husk",
    "rustic_engineer:airship",
    "alexscaves:deep_one",
    "alexsmobs:crow",
    "rustic_engineer:wooden_cube_chest",
    "alexsmobs:guster",
    "irons_spellbooks:magehunter_vindicator",
    "minecraft:chicken",
    "alexsmobs:giant_squid",
    "minecraft:zombie",
    "iceandfire:dread_knight",
    "graveyard:acolyte",
    "alexsmobs:emu",
    "samurai_dynasty:komainu",
    "aquaculture:tambaqui",
    "alexscaves:licowitch",
    "alexsmobs:flutter",
    "minecraft:hoglin",
    "mythicmounts:netherbat",
    "player_companions:small_slime",
    "ars_nouveau:cascading_weald_walker",
    "gore:husk_without_legs_and_arm",
    "aquaculture:brown_shrooma",
    "iceandfire:myrmex_swarmer",
    "minecraft:zombified_piglin",
    "naturalist:rattlesnake",
    "minecraft:sheep",
    "mythicmounts:griffon",
    "rustic_engineer:spider_mech",
    "graveyard:ghoul",
    "samurai_dynasty:akaname",
    "naturalist:robin",
    "naturalist:tortoise",
    "alexsmobs:bone_serpent_part",
    "alexsmobs:raccoon",
    "minecraft:ravager",
    "alexsmobs:bone_serpent",
    "iceandfire:myrmex_soldier",
    "ars_nouveau:whirlisprig",
    "mythicmounts:courierbird",
    "iceandfire:pixie",
    "crabbersdelight:crab",
    "mythicmounts:moth",
    "alexsmobs:mudskipper",
    "iceandfire:myrmex_sentinel",
    "alexsmobs:crimson_mosquito",
    "creeperoverhaul:beach_creeper",
    "mythicmounts:nightmare",
    "gore:husk_without_mouth_and_arm",
    "creeperoverhaul:hills_creeper",
    "alexsmobs:jerboa",
    "endermanoverhaul:spirit",
    "alexsmobs:comb_jelly",
    "player_companions:firefly",
    "naturalist:hippo",
    "creeperoverhaul:bamboo_creeper",
    "naturalist:snake",
    "railways:conductor",
    "player_companions:dobutsu",
    "naturalist:catfish",
    "gore:husk_without_legs",
    "alexsmobs:enderiophage",
    "alexsmobs:sunbird",
    "steam_powered:tri_wheeler",
    "iceandfire:myrmex_worker",
    "gore:husk_without_mouth_and_arms",
    "minecraft:cat",
    "ars_nouveau:amethyst_golem",
    "naturalist:lizard",
    "minecraft:tropical_fish",
    "naturalist:snail",
    "alexscaves:gloomoth",
    "alexscaves:vesper",
    "naturalist:finch",
    "alexscaves:lanternfish",
    "minecraft:zombie_villager",
    "gore:dismembered_spider_1",
    "alexsmobs:froststalker",
    "gore:dismembered_spider_2",
    "minecraft:giant",
    "cave_dweller:cave_dweller",
    "alexsmobs:lobster",
    "mowziesmobs:lantern",
    "alexsmobs:seagull",
    "endermanoverhaul:end_enderman",
    "aquaculture:atlantic_herring",
    "alexscaves:brainiac",
    "endermanoverhaul:soulsand_valley_enderman",
    "aquamirae:tortured_soul",
    "gore:dismembered_spider_3",
    "ars_nouveau:wilden_stalker",
    "creeperoverhaul:cave_creeper",
    "steam_powered:surface_crawler",
    "aquaculture:bluegill",
    "minecraft:husk",
    "naturalist:firefly",
    "gore:zombie_without_mouth_and_arm",
    "mowziesmobs:umvuthana",
    "alexscaves:luxtructosaurus",
    "deeperdarker:sculk_centipede",
    "minecraft:donkey",
    "mowziesmobs:umvuthana_crane_player",
    "mutantmonsters:mutant_skeleton",
    "minecraft:piglin_brute",
    "aquamirae:golden_moth",
    "naturalist:giraffe",
    "samurai_dynasty:raijin",
    "deeperdarker:stalker",
    "aquaculture:jellyfish",
    "alexsmobs:frilled_shark",
    "player_companions:snail",
    "alexsmobs:bald_eagle",
    "endermanoverhaul:scarab",
    "iceandfire:ice_dragon",
    "samurai_dynasty:twotailed",
    "graveyard:nameless_hanged",
    "alexsmobs:blobfish",
    "alexscaves:gum_worm",
    "aquaculture:blackfish",
    "alexsmobs:void_worm",
    "alexscaves:sweetish_fish",
    "minecraft:parrot",
    "aquamirae:spinefish",
    "irons_spellbooks:apothecarist",
    "argentinas_delight:pollomuerto",
    "alexsmobs:centipede_head",
    "aquaculture:carp",
    "creeperoverhaul:desert_creeper",
    "iceandfire:sea_serpent",
    "mythicmounts:ridinglizard",
    "alexsmobs:banana_slug",
    "mutantmonsters:mutant_creeper",
    "naturalist:alligator",
    "aquaculture:boulti",
    "alexsmobs:bunfungus",
    "gore:wither_skeleton_condemned",
    "minecraft:mule",
    "naturalist:boar",
    "ribbits:ribbit",
    "minecraft:vindicator",
    "mythicmounts:dragon",
    "alexsmobs:flying_fish",
    "aquaculture:synodontis",
    "creeperoverhaul:mushroom_creeper",
    "samurai_dynasty:fujin",
    "graveyard:ghouling",
    "steam_powered:giant_crab",
    "irons_spellbooks:debug_wizard",
    "graveyard:revenant",
    "irons_spellbooks:spectral_steed",
    "burnt:tomb_spawner",
    "ars_nouveau:familiar_whirlisprig",
    "mythicmounts:geckotoalizard",
    "gore:experiment_iv",
    "graveyard:corrupted_pillager",
    "creeperoverhaul:badlands_creeper",
    "creeperoverhaul:snowy_creeper",
    "gore:zombie_without_legs_and_arm",
    "aquaculture:catfish",
    "burnt:burnt_forest_spawner",
    "aquamirae:luminous_jelly",
    "alexsmobs:terrapin",
    "burnt:grave_spawner",
    "iceandfire:lightning_dragon",
    "minecraft:pig",
    "alexsmobs:alligator_snapping_turtle",
    "aquaculture:atlantic_halibut",
    "creeperoverhaul:swamp_creeper",
    "endermanoverhaul:crimson_forest_enderman",
    "iceandfire:fire_dragon",
    "minecraft:cod",
    "aquaculture:red_grouper",
    "gore:experiment_iv_i",
    "alexsmobs:platypus",
    "minecraft:cow",
    "alexsmobs:rocky_roller",
    "aquaculture:rainbow_trout",
    "naturalist:duck",
    "alexsmobs:soul_vulture",
    "gore:zombie_on_burn",
    "alexsmobs:blue_jay",
    "iceandfire:dread_scuttler",
    "minecraft:salmon",
    "mowziesmobs:naga",
    "alexsmobs:anteater",
    "alexsmobs:rain_frog",
    "burnt:wisp",
    "mowziesmobs:ferrous_wroughtnaut",
    "minecraft:rabbit",
    "minecraft:pillager",
    "minecraft:zoglin",
    "gore:husk_without_head",
    "aquaculture:piranha",
    "naturalist:butterfly",
    "alexsmobs:leafcutter_ant",
    "player_companions:raptor",
    "ars_nouveau:wilden_guardian",
    "aquamirae:captain_cornelia",
    "creeperoverhaul:jungle_creeper",
    "irons_spellbooks:cryomancer",
    "deeperdarker:shriek_worm",
    "iceandfire:gorgon",
    "naturalist:lion",
    "graveyard:corrupted_vindicator",
    "aquaculture:arrau_turtle",
    "naturalist:canary",
    "alexsmobs:gazelle",
    "gore:cutted_horizonal_zombie",
    "minecraft:sniffer",
    "endermanoverhaul:windswept_hills_enderman",
    "iceandfire:cockatrice",
    "gore:cutted_horizontal_husk",
    "gore:old_wither_skeleton_condemned",
    "samurai_dynasty:onibi",
    "gore:without_head_spider",
    "alexscaves:watcher",
    "gore:akeriskull_entity",
    "naturalist:coral_snake",
    "endermanoverhaul:end_islands_enderman",
    "deeperdarker:sculk_snapper",
    "mowziesmobs:umvuthana_follower_player",
    "iceandfire:deathworm",
    "endermanoverhaul:warped_forest_enderman",
    "alexsmobs:seal",
    "alexsmobs:roadrunner",
    "alexsmobs:laviathan",
    "minecraft:trader_llama",
    "samurai_dynasty:enenra",
    "irons_spellbooks:necromancer",
    "iceandfire:dread_lich",
    "aquaculture:bayad",
    "alexsmobs:maned_wolf",
    "graveyard:skeleton_creeper",
    "minecraft:dolphin",
    "endermanoverhaul:badlands_enderman",
    "alexsmobs:gelada_monkey",
    "gore:zombie_without_head_and_arm",
    "alexsmobs:dropbear",
    "alexsmobs:tiger",
    "player_companions:fairy",
    "alexscaves:caramel_cube",
    "minecraft:bee",
    "aquaculture:perch",
    "alexsmobs:devils_hole_pupfish",
    "minecraft:illusioner",
    "gore:hello_kid",
    "endermanoverhaul:axolotl_pet_enderman",
    "alexsmobs:bison",
    "mowziesmobs:foliaath",
    "mowziesmobs:frostmaw",
    "minecraft:drowned",
    "mythicmounts:nudibranch",
    "aquaculture:arapaima",
    "alexsmobs:tusklin",
    "naturalist:elephant",
    "alexsmobs:underminer",
    "mythicmounts:direwolf",
    "minecraft:wandering_trader",
    "alexscaves:gumbeeper",
    "deeperdarker:angler_fish",
    "mythicmounts:colelytra",
    "iceandfire:stone_statue",
    "create_sa:brass_drone",
    "alexscaves:boundroid",
    "mowziesmobs:umvuthana_raptor",
    "endermanoverhaul:cave_enderman",
    "endermanoverhaul:mushroom_fields_enderman",
    "aquaculture:atlantic_cod",
    "graveyard:wraith",
    "minecraft:pufferfish",
    "aquaculture:starshell_turtle",
    "minecraft:fox",
    "mowziesmobs:umvuthana_crane",
    "mythicmounts:firebird",
    "alexsmobs:warped_toad",
    "gore:experiment_i",
    "alexsmobs:cockroach",
    "creeperoverhaul:savannah_creeper",
    "gore:squitchgun_flame_fire",
    "endermanoverhaul:pet_enderman",
    "naturalist:rhino",
    "alexscaves:ferrouslime",
    "alexsmobs:capuchin_monkey",
    "minecraft:polar_bear",
    "aquaculture:brown_trout",
    "endermanoverhaul:ice_spikes_enderman",
    "minecraft:turtle",
    "alexsmobs:rattlesnake",
    "wom:lupus_rex",
    "ars_nouveau:familiar_starbuncle",
    "rustic_engineer:submarine_abyssal",
    "ars_nouveau:starbuncle",
    "deeperdarker:sculk_leech",
    "alexsmobs:potoo",
    "samurai_dynasty:jorogumo",
    "alexsmobs:fly",
    "alexscaves:trilocaris",
    "irons_spellbooks:dead_king",
    "gore:warden_death",
    "alexsmobs:straddler",
    "deeperdarker:sludge",
    "mythicmounts:archelon",
    "alexsmobs:sea_bear",
    "alexscaves:nucleeper",
    "alexscaves:hullbreaker",
    "mowziesmobs:umvuthana_follower_raptor",
    "alexsmobs:sugar_glider",
    "endermanoverhaul:swamp_enderman",
    "naturalist:bass",
    "aquamirae:eel",
    "alexsmobs:orca",
    "gore:zombie_without_mouth_and_arms",
    "naturalist:dragonfly",
    "irons_spellbooks:priest",
    "iceandfire:troll",
    "minecraft:bat",
    "naturalist:sparrow",
    "alexsmobs:cosmaw",
    "iceandfire:amphithere",
    "mythicmounts:acencia",
    "ars_nouveau:familiar_amethyst_golem",
    "naturalist:lizard_tail",
    "naturalist:caterpillar",
    "alexsmobs:skunk",
    "aquamirae:anglerfish",
    "alexsmobs:tasmanian_devil",
    "gore:zombie_without_mouth",
    "alexsmobs:stradpole",
    "iceandfire:stymphalian_bird",
    "iceandfire:hippogryph",
    "endermanoverhaul:savanna_enderman",
    "minecraft:panda",
    "endermanoverhaul:coral_enderman",
    "gore:multiple_cuts_zombie",
    "burnt:soul_spawner",
    "alexsmobs:moose",
    "alexsmobs:shoebill",
    "alexsmobs:farseer",
    "ars_nouveau:vexing_weald_walker",
    "alexsmobs:warped_mosco",
    "iceandfire:cyclops",
    "alexsmobs:komodo_dragon",
    "endermanoverhaul:dark_oak_enderman",
    "alexscaves:forsaken",
    "aquamirae:maze_mother",
    "alexscaves:mine_guardian",
    "gore:husk_without_head_and_arm",
    "irons_spellbooks:summoned_polar_bear",
    "alexsmobs:crocodile",
    "alexscaves:teletor",
    "irons_spellbooks:cultist",
    "alexsmobs:triops",
    "alexsmobs:rhinoceros",
    "aquaculture:tuna",
    "argentinas_delight:chanchomuerto",
    "gore:horizontal_cutted_spider",
    "naturalist:deer",
    "alexsmobs:mimicube",
    "player_companions:welsh_corgi",
    "ars_nouveau:familiar_bookwyrm",
    "alexscaves:gingerbread_man",
    "minecraft:frog",
    "alexsmobs:mimic_octopus",
    "alexsmobs:void_worm_part",
    "gore:zombie_without_legs",
    "alexscaves:caniac",
    "iceandfire:hydra",
    "aquamirae:pillagers_patrol",
    "player_companions:lizard",
    "minecraft:evoker",
    "iceandfire:dread_ghoul",
    "alexsmobs:tarantula_hawk",
    "ars_nouveau:blazing_weald_walker",
    "aquaculture:smallmouth_bass",
    "alexsmobs:cachalot_whale",
    "endermanoverhaul:nether_wastes_enderman",
    "creeperoverhaul:ocean_creeper",
    "rustic_engineer:wooden_cube",
    "alexscaves:gammaroach",
    "creeperoverhaul:dark_oak_creeper",
    "graveyard:lich",
    "aquaculture:minnow",
    "alexscaves:notor",
    "gore:experiment_iii",
    "ars_nouveau:wilden_hunter",
    "iceandfire:dread_horse",
    "alexsmobs:anaconda",
    "gore:flesh_demon",
    "irons_spellbooks:summoned_zombie",
    "mowziesmobs:grottol",
    "aquaculture:red_shrooma",
    "mowziesmobs:baby_foliaath",
    "minecraft:goat",
    "player_companions:small_ghast",
    "mutantmonsters:mutant_enderman",
    "aquaculture:gar",
    "iceandfire:dread_beast",
    "alexsmobs:mantis_shrimp",
    "mutantmonsters:spider_pig",
    "samurai_dynasty:kitsune",
    "endermanoverhaul:snowy_enderman",
    "gore:hlvrek",
    "mowziesmobs:umvuthi",
    "create_dd:seething_ablaze",
    "alexscaves:radgill",
    "iceandfire:hippocampus",
    "ars_nouveau:familiar_drygmy",
    "alexsmobs:toucan",
    "naturalist:bluejay",
    "iceandfire:myrmex_queen",
    "player_companions:pig",
    "gore:vertical_cutted_spider",
    "ars_nouveau:flourishing_weald_walker",
    "iceandfire:ghost",
    "gore:cutted_vertical_husk",
    "iceandfire:myrmex_royal",
    "irons_spellbooks:pyromancer",
    "alexsmobs:murmur",
    "aquaculture:box_turtle",
    "samurai_dynasty:tanuki",
    "gore:the_executioner",
    "argentinas_delight:vacamuertamob",
    "creeperoverhaul:dripstone_creeper",
    "irons_spellbooks:summoned_skeleton",
    "ars_nouveau:summon_skeleton",
    "iceandfire:dread_thrall",
    "alexsmobs:mungus",
    "player_companions:rooster",
    "alexsmobs:caiman",
    "alexsmobs:spectre",
    "irons_spellbooks:citadel_keeper",
    "ars_nouveau:summon_horse",
    "alexsmobs:catfish",
    "aquaculture:pollock",
    "mutantmonsters:endersoul_clone",
    "minecraft:piglin",
    "alexsmobs:skelewag",
    "create_dd:inert_blazeling",
    "epicfight:wither_ghost",
    "alexscaves:boundroid_winch",
    "alexscaves:deep_one_knight",
    "alexsmobs:elephant",
    "aquaculture:capitaine",
    "argentinas_delight:ovejamuerta",
    "gore:husk_without_mouth",
    "minecraft:zombie_horse",
    "minecraft:camel",
    "deeperdarker:shattered",
    "ars_nouveau:summon_wolf",
    "minecraft:ocelot",
    "minecraft:wolf"
]
